apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-mail
data:
    server: {{ .Values.app.mail.server | quote }}
    port: {{ .Values.app.mail.port | quote }}
    encryption: {{ .Values.app.mail.encryption | quote }}
    
    



