{{- if .Values.postgres.incluster }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-postgres-config
data:
    postgresql.conf: |
        #------------------------------------------------------------------------------
        # CUSTOMIZED OPTIONS
        #------------------------------------------------------------------------------
        listen_addresses = '*'
        #PG hero stats
        shared_preload_libraries = 'pg_stat_statements'
        pg_stat_statements.track = all
        
        #Tune DB
        max_connections = 1000
        shared_buffers = 512MB
        effective_cache_size = 1536MB
        maintenance_work_mem = 128MB
        checkpoint_completion_target = 0.7
        wal_buffers = 16MB
        default_statistics_target = 100
        random_page_cost = 1.1
        effective_io_concurrency = 200
        work_mem = 524kB
        min_wal_size = 1GB
        max_wal_size = 4GB
        max_worker_processes = 2
        max_parallel_workers_per_gather = 1
        max_parallel_workers = 2
        max_parallel_maintenance_workers = 1
{{- end }}