apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres
type: Opaque
stringData:
  username: {{ .Values.postgres.username | quote }}
  password: {{ .Values.postgres.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-s3
type: Opaque
stringData:
  key: {{ .Values.app.s3.key | quote }}
  secret: {{ .Values.app.s3.secret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mail
type: Opaque
stringData:
  username: {{ .Values.app.mail.username | quote }}
  password: {{ .Values.app.mail.password | quote }}
---  
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-adminer
type: Opaque
stringData:
  username: {{ .Values.app.adminer.username | quote }}
  password: {{ .Values.app.adminer.password | quote }}






